import { ThemeCustomizer, ThemeCustomizerSection } from '@modular-app/core/types/theme';

export interface CustomizerConfig extends ThemeCustomizer {
  panels?: Array<{
    id: string;
    title: string;
    description?: string;
    priority?: number;
  }>;
}

export const customizerConfig: CustomizerConfig = {
  panels: [
    {
      id: 'appearance',
      title: 'Appearance',
      description: 'Customize the visual appearance of your theme',
      priority: 10,
    },
    {
      id: 'layout',
      title: 'Layout & Structure',
      description: 'Configure layout and structural elements',
      priority: 20,
    },
    {
      id: 'content',
      title: 'Content Settings',
      description: 'Content display and formatting options',
      priority: 30,
    },
  ],
  sections: [
    {
      id: 'site_identity',
      title: 'Site Identity',
      description: 'Customize your site logo and identity',
      panel: 'appearance',
      priority: 10,
      settings: [
        {
          id: 'site_logo',
          type: 'image',
          label: 'Site Logo',
          description: 'Upload your site logo',
          default: '',
          transport: 'postMessage',
          validation: {
            required: false,
          },
        },
        {
          id: 'site_icon',
          type: 'image',
          label: 'Site Icon (Favicon)',
          description: 'Upload a site icon (32x32px recommended)',
          default: '',
          transport: 'refresh',
        },
        {
          id: 'logo_width',
          type: 'range',
          label: 'Logo Width',
          description: 'Adjust the logo width in pixels',
          default: 200,
          min: 100,
          max: 400,
          step: 10,
          transport: 'postMessage',
        },
      ],
    },
    {
      id: 'colors',
      title: 'Colors',
      description: 'Customize theme colors and color scheme',
      panel: 'appearance',
      priority: 20,
      settings: [
        {
          id: 'primary_color',
          type: 'color',
          label: 'Primary Color',
          description: 'Main brand color used throughout the site',
          default: '#3b82f6',
          transport: 'postMessage',
        },
        {
          id: 'secondary_color',
          type: 'color',
          label: 'Secondary Color',
          description: 'Secondary accent color',
          default: '#64748b',
          transport: 'postMessage',
        },
        {
          id: 'link_color',
          type: 'color',
          label: 'Link Color',
          description: 'Color for links and interactive elements',
          default: '#3b82f6',
          transport: 'postMessage',
        },
        {
          id: 'text_color',
          type: 'color',
          label: 'Text Color',
          description: 'Main text color',
          default: '#1f2937',
          transport: 'postMessage',
        },
        {
          id: 'background_color',
          type: 'color',
          label: 'Background Color',
          description: 'Main background color',
          default: '#ffffff',
          transport: 'postMessage',
        },
      ],
    },
    {
      id: 'typography',
      title: 'Typography',
      description: 'Font and text styling options',
      panel: 'appearance',
      priority: 30,
      settings: [
        {
          id: 'heading_font_family',
          type: 'select',
          label: 'Heading Font Family',
          description: 'Font family for headings (h1, h2, h3, etc.)',
          default: 'Inter',
          choices: {
            'Inter': 'Inter',
            'Roboto': 'Roboto',
            'Poppins': 'Poppins',
            'Merriweather': 'Merriweather',
            'Playfair Display': 'Playfair Display',
            'Montserrat': 'Montserrat',
          },
          transport: 'postMessage',
        },
        {
          id: 'body_font_family',
          type: 'select',
          label: 'Body Font Family',
          description: 'Font family for body text',
          default: 'Inter',
          choices: {
            'Inter': 'Inter',
            'Roboto': 'Roboto',
            'Source Sans Pro': 'Source Sans Pro',
            'Open Sans': 'Open Sans',
            'Lato': 'Lato',
            'PT Sans': 'PT Sans',
          },
          transport: 'postMessage',
        },
        {
          id: 'font_size_base',
          type: 'range',
          label: 'Base Font Size',
          description: 'Base font size in pixels',
          default: 16,
          min: 14,
          max: 20,
          step: 1,
          transport: 'postMessage',
        },
        {
          id: 'line_height_base',
          type: 'range',
          label: 'Line Height',
          description: 'Base line height ratio',
          default: 1.6,
          min: 1.2,
          max: 2.0,
          step: 0.1,
          transport: 'postMessage',
        },
      ],
    },
    {
      id: 'header',
      title: 'Header',
      description: 'Header layout and display options',
      panel: 'layout',
      priority: 10,
      settings: [
        {
          id: 'header_layout',
          type: 'radio',
          label: 'Header Layout',
          description: 'Choose the header layout style',
          default: 'default',
          choices: {
            'default': 'Default (Logo left, Menu right)',
            'centered': 'Centered (Logo center, Menu below)',
            'minimal': 'Minimal (Logo only)',
          },
          transport: 'refresh',
        },
        {
          id: 'header_sticky',
          type: 'checkbox',
          label: 'Sticky Header',
          description: 'Make header stick to top when scrolling',
          default: true,
          transport: 'refresh',
        },
        {
          id: 'show_search_header',
          type: 'checkbox',
          label: 'Show Search in Header',
          description: 'Display search form in the header',
          default: true,
          transport: 'postMessage',
        },
        {
          id: 'header_background_color',
          type: 'color',
          label: 'Header Background',
          description: 'Header background color',
          default: '#ffffff',
          transport: 'postMessage',
        },
      ],
    },
    {
      id: 'layout_general',
      title: 'General Layout',
      description: 'Overall layout and container settings',
      panel: 'layout',
      priority: 20,
      settings: [
        {
          id: 'container_width',
          type: 'range',
          label: 'Container Max Width',
          description: 'Maximum content width in pixels',
          default: 1200,
          min: 960,
          max: 1600,
          step: 40,
          transport: 'postMessage',
        },
        {
          id: 'sidebar_position',
          type: 'radio',
          label: 'Sidebar Position',
          description: 'Position of the main sidebar',
          default: 'right',
          choices: {
            'left': 'Left',
            'right': 'Right',
            'none': 'No Sidebar',
          },
          transport: 'refresh',
        },
        {
          id: 'sidebar_width',
          type: 'range',
          label: 'Sidebar Width',
          description: 'Sidebar width as percentage of container',
          default: 30,
          min: 20,
          max: 40,
          step: 5,
          transport: 'postMessage',
        },
        {
          id: 'content_spacing',
          type: 'range',
          label: 'Content Spacing',
          description: 'Spacing between content elements',
          default: 2,
          min: 1,
          max: 4,
          step: 0.5,
          transport: 'postMessage',
        },
      ],
    },
    {
      id: 'footer',
      title: 'Footer',
      description: 'Footer layout and content settings',
      panel: 'layout',
      priority: 30,
      settings: [
        {
          id: 'footer_layout',
          type: 'radio',
          label: 'Footer Layout',
          description: 'Choose footer column layout',
          default: 'three-columns',
          choices: {
            'one-column': 'Single Column',
            'two-columns': 'Two Columns',
            'three-columns': 'Three Columns',
            'four-columns': 'Four Columns',
          },
          transport: 'refresh',
        },
        {
          id: 'footer_background_color',
          type: 'color',
          label: 'Footer Background',
          description: 'Footer background color',
          default: '#1f2937',
          transport: 'postMessage',
        },
        {
          id: 'footer_text_color',
          type: 'color',
          label: 'Footer Text Color',
          description: 'Footer text color',
          default: '#d1d5db',
          transport: 'postMessage',
        },
        {
          id: 'show_footer_copyright',
          type: 'checkbox',
          label: 'Show Copyright Notice',
          description: 'Display copyright notice in footer',
          default: true,
          transport: 'postMessage',
        },
        {
          id: 'footer_copyright_text',
          type: 'textarea',
          label: 'Copyright Text',
          description: 'Custom copyright text (leave empty for auto-generated)',
          default: '',
          transport: 'postMessage',
        },
      ],
    },
    {
      id: 'blog',
      title: 'Blog Settings',
      description: 'Blog layout and display options',
      panel: 'content',
      priority: 10,
      settings: [
        {
          id: 'blog_layout',
          type: 'radio',
          label: 'Blog Layout',
          description: 'Layout for blog post listings',
          default: 'grid',
          choices: {
            'list': 'List View',
            'grid': 'Grid View (2 columns)',
            'grid-3': 'Grid View (3 columns)',
            'masonry': 'Masonry Layout',
          },
          transport: 'refresh',
        },
        {
          id: 'excerpt_length',
          type: 'range',
          label: 'Excerpt Length',
          description: 'Number of words in post excerpts',
          default: 50,
          min: 20,
          max: 100,
          step: 5,
          transport: 'postMessage',
        },
        {
          id: 'show_featured_image',
          type: 'checkbox',
          label: 'Show Featured Images',
          description: 'Display featured images in post listings',
          default: true,
          transport: 'postMessage',
        },
        {
          id: 'show_post_meta',
          type: 'checkbox',
          label: 'Show Post Meta',
          description: 'Display post date, author, categories',
          default: true,
          transport: 'postMessage',
        },
        {
          id: 'show_read_more',
          type: 'checkbox',
          label: 'Show Read More Button',
          description: 'Display "Read More" button on excerpts',
          default: true,
          transport: 'postMessage',
        },
      ],
    },
    {
      id: 'single_post',
      title: 'Single Post',
      description: 'Individual post display settings',
      panel: 'content',
      priority: 20,
      settings: [
        {
          id: 'show_author_bio',
          type: 'checkbox',
          label: 'Show Author Bio',
          description: 'Display author biography on single posts',
          default: true,
          transport: 'postMessage',
        },
        {
          id: 'show_related_posts',
          type: 'checkbox',
          label: 'Show Related Posts',
          description: 'Display related posts at end of post',
          default: true,
          transport: 'postMessage',
        },
        {
          id: 'related_posts_count',
          type: 'range',
          label: 'Related Posts Count',
          description: 'Number of related posts to show',
          default: 3,
          min: 2,
          max: 6,
          step: 1,
          transport: 'postMessage',
        },
        {
          id: 'show_post_navigation',
          type: 'checkbox',
          label: 'Show Post Navigation',
          description: 'Show previous/next post navigation',
          default: true,
          transport: 'postMessage',
        },
        {
          id: 'enable_comments',
          type: 'checkbox',
          label: 'Enable Comments',
          description: 'Allow comments on posts',
          default: true,
          transport: 'refresh',
        },
      ],
    },
    {
      id: 'performance',
      title: 'Performance',
      description: 'Performance and optimization settings',
      panel: 'content',
      priority: 30,
      settings: [
        {
          id: 'lazy_load_images',
          type: 'checkbox',
          label: 'Lazy Load Images',
          description: 'Load images only when they enter viewport',
          default: true,
          transport: 'refresh',
        },
        {
          id: 'optimize_fonts',
          type: 'checkbox',
          label: 'Optimize Font Loading',
          description: 'Enable font display optimization',
          default: true,
          transport: 'refresh',
        },
        {
          id: 'minify_css',
          type: 'checkbox',
          label: 'Minify CSS',
          description: 'Minify CSS output for better performance',
          default: true,
          transport: 'refresh',
        },
        {
          id: 'enable_dark_mode',
          type: 'checkbox',
          label: 'Enable Dark Mode',
          description: 'Allow users to switch to dark mode',
          default: true,
          transport: 'postMessage',
        },
      ],
    },
  ],
};

export default customizerConfig;